### ISSUE TITLE
imagegif function doesn't have quality argument

### ISSUE THREAD

**Issue by peter279k** [jenstornell/php-image-converter#11]
According to the [imagegif](https://www.php.net/manual/en/function.imagegif.php) function reference, this doesn't have the `$quality` argument.

And in our source [code snippets](https://github.com/jenstornell/php-image-converter/blob/master/src/ImageConverter.php#L90), this `$quality` parameter should be removed from `imagegif` function.

**Comment by jenstornell** [comment]
Ahh, I see. Now that we have switch case instead, it make perfect sense to remove it.

**Comment by peter279k** [comment]
That's why we use the `switch..case` rather than string function mapping :) because it's easy for us to debug.

**Comment by jenstornell** [comment]
✔️
