### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/php-image-converter#20]
Add multiple issue templates, one for new features and one for new issues. Maybe even one for questions as well. https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by peter279k** [comment]
It's related to PR #19.

**Comment by jenstornell** [comment]
I added three issue templates (on a bus with my phone). You can improve them if needed. I like to keep them short to not make each issue a pain.
