### ISSUE TITLE
Revert converImage function helper

### ISSUE THREAD

**Issue by peter279k** [jenstornell/php-image-converter#5]
As title, It's related to PR #3.

I try removing the `convertImage` function and using the `ImageConverter` class directly.

The `convertImage` is unnecessary because we can use the `ImageConverter` class directly.

Once the PR #3 is approved, I can do this to update the `example`.

**Comment by jenstornell** [comment]
>The convertImage is unnecessary because we can use the ImageConverter class directly.

Well, both yes and no.

**Compare this...**

```php
convertImage('./image.png', './image.webp', 5);
```

**...to this...**

```php
use Jens\ImageConverter\ImageConverter;
$from = __DIR__ . '/tests/fixtures/from/dices.png';
$to = __DIR__ . '/tests/fixtures/to/dices.webp';
$converter = new ImageConverter();
echo $converter->convert($from, $to, 5);
```

I added the helper function to keep it short and clean. With a bunch of other code around, it's nice with a oneliner.

On the other hand, the function name can already be taken by something else. Also, a new class instance is created for every time the function runs. That's probably bad practice.

With other libraries I often make my own wrapper function to keep the code at a minimum. Maybe that's the best way in this case as well, to let the user figure out an own implementation that works best for him/her? (skipping the built in helper function)

**Comment by peter279k** [comment]
Hi @jenstornell, thank you for your reply.

You're right. If we keep the helper function existed, it can let the code be clean.

And it also has the good practice in the code.

Maybe I can revert the helper function after the PR #3 is merged.

And the helper function should have the namespace to avoid collision function name issue :).

**Comment by jenstornell** [comment]
I re-added the helper function. I close this.
