### ISSUE TITLE
Better shorter namespace?

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/php-image-converter#6]
**The old syntax without namespace looks like this:**

```php
convertImage('./image.png', './image.webp', 5);
```

**The new syntax will probably look something like this:**

```php
\Jens\ImageConverter\convertImage('./image.png', './image.webp', 5);
```

I don't really like the namespace, but I don't have a better suggestion at the moment.

**Another idea**

```php
\ImageConverter\convert('./image.png', './image.webp', 5);
```

It's probably too generic, but I like the look of it better (I also changed the function name). It needs some more thought.

The reason I think it's important to get it right is that it's probably the only line of code most people will use. The rest is "hidden" in the class behind it.

**Comment by peter279k** [comment]
@jenstornell, thank you for your concern.

I also prefer this `\ImageConverter\convert('./image.png', './image.webp', 5);` would be great.

**Comment by jenstornell** [comment]
I added the new namespace and changed the `example.php` with it.

I was not sure if there was a good reason to keep the class call version. I removed it, but we can re-add it if it make sense.
