### ISSUE TITLE
Rethink about the string function call mapping

### ISSUE THREAD

**Issue by peter279k** [jenstornell/php-image-converter#7]
As title, please look at this [code](https://github.com/jenstornell/php-image-converter/blob/master/src/ImageConverter.php#L51) firstly.

It seems that we use the string function call mapping to dispatch the current `imagecreatefrom` and `image` function name.

But this approach is possible to cause some issues:

- This should let us be hard to do debugging/reading work.
- Don't make sure that this performance would be good.

I think we can consider using the `switch......case` to dispatch the current image functions.

**Comment by jenstornell** [comment]
@peter279k I was from the start inspired by this repo:

https://github.com/rakibtg/PHP-ImageToWebp/blob/master/ImageToWebp.php#L13

He uses switch case like your suggestion. I tried to be smart and save 10 rows of code, but I think you are right. We don't need to be smart here and a switch case may be better readability as well.

Good suggestion!

**Comment by jenstornell** [comment]
✔️
